# GoReleaser configuration for kat
before:
  hooks:
    - go mod download
    - go mod tidy

report_sizes: true

builds:
  - main: ./cmd/kat/
    id: "kat"
    binary: kat
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/BolajiOlajide/kat/internal/version.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false
    name_template: >-
      kat_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: BolajiOlajide
    name: kat
  draft: true
  replace_existing_draft: true
  mode: append
  # Header for the release body.
  #
  # Templates: allowed.
  header: |
    ## Kat ({{ .Version }})

    Welcome to this new release!
