# Theme settings
doks:
    baseurl: ""
    # Available themes: blue (default), green, purple, red and yellow
    color_theme: green
    header:
        logo:
            text: Kat
            image:
        nav:
            # - item_name: Item 1
            #   item_url: '#'
            # - item_name: Item 2
            #   item_url: '#'
            - item_name: View on GitHub
              item_url: 'https://github.com/BolajiOlajide/kat'
              external_url: true
              icon: github
    footer:
        content:
            logo:
                text: Kat
                image:
            copyright: Copyright &copy; 2023 - Present. All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/BolajiOlajide'
            - network_name: twitter
              profile_url: 'https://x.com/Bolaji___'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCynulnc9t2YbpMENu0npmMA'
    google_analytics:
        # Add your Google Analytics tracking code to activate Google Analytics
        tracking_code: 'G-5XYGPTW4LV'
    comments:
        disqus_forum_shortname: ""

# SASS settings
sass:
    sass_dir: ./doc/_sass
    style: compressed

# Jekyll settings
layouts_dir: ./doc/_layouts
includes_dir: ./doc/_includes
exclude: [ 'kat.go', 'README.md', 'CHANGELOG.md', 'internal/', 'cmd/', '.github/', 'examples/', 'go.mod', 'go.sum', 'Makefile', 'LICENSE', 'install.sh', 'doks' ]
permalink: /:title/
plugins:
  - jekyll-redirect-from
