on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: test
      run: go test -v ./...
